version: '3.8'

services:
  currency-db:
    image: postgres:16
    container_name: currency-db
    restart: always
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: currencyuser
      POSTGRES_PASSWORD: currencypass
    ports:
      - "5432:5432"
    volumes:
      - currencydata:/var/lib/postgresql/data

volumes:
  currencydata:
